config/routes.rb
Idu0200::Application.routes.draw do

  resources :devices do
    collection do
      get 'search'
      get 'add_device_to_order'
      post 'search'
    end
  end

  devise_for :user_accounts
  root :to => redirect('/service_requests')
  get 'customer/find_customer'
  get 'customer/find_employee'
  match '/get_default_price',  to: 'service_types#get_default_price',         via: 'get'
  match '/delete_service_action',  to: 'service_orders#delete_service_action',         via: 'delete'
  resources :service_requests do
    resources :service_orders do
    end
  end

end

app/models/device.rb
class Device < ActiveRecord::Base
  self.table_name = 'device'
  self.primary_key = :device
  belongs_to :device_type, foreign_key: 'device_type_fk'
  has_many :service_devices, foreign_key: 'device_fk'

  validates_presence_of :name
  validates_length_of :reg_no, maximum: 100
  validates_format_of :manufacturer, :with => /\A[A-Za-z ]+\Z/, message: 'Ainult tähed on lubatud'

end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    self.table_name = 'device_type'
    self.primary_key = :device_type

    def sub_types
      DeviceType.where(level:2, super_type_fk:self.device_type)
    end

    def label
      self.type_name
    end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  require 'will_paginate/array'

  respond_to :html

  def index
    @devices = Device.includes(:device_type).order('device_type.type_name').paginate(:page => params[:page], :per_page => 25)
    respond_with(@devices)
  end

  def show
    respond_with(@device)
  end

  def new
    @device = Device.new
    respond_with(@device)
  end

  def edit
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      if params[:service_order] && params[:service_order][:id]
        @service_order = ServiceOrder.find_by(service_order: params[:service_order][:id].to_i)
        unless @service_order.nil?
          ServiceDevice.create(service_order_fk: @service_order.service_order, device_fk: @device.device, service_device_status_type_fk: 1)
          redirect_to edit_service_request_service_order_path(@service_order.service_request, @service_order)
          flash[:info] = 'Uus toode lisatud'
          return
        end
      end
      redirect_to edit_device_path(@device), notice: 'Seadme andmed salvestatud'
    else
      render action: 'new'
    end
  end

  def update
    if @device.update(device_params)
      redirect_to edit_device_path(@device), notice: 'Seadme andmed salvestatud'
    else
      render action: 'edit'
    end
  end

  def destroy
    if @device.service_devices.size > 0
      flash[:error] = 'Seadet ei saa kustutada, kuna see on seotud juba mõne tellimusega'
    else
      @device.destroy
    end
    redirect_to devices_path
  end

  def search
    @device_search = DeviceSearch.new
    if request.post?
      if get_where_clause.size == 0
        flash.now[:error] = 'Sisestage vähemalt 1 otsingu parameeter'
        return
      end
      @devices = Device.find_by_sql([get_search_select, *get_params]).paginate(:page => params[:page], :per_page => 25)
      @device_search = DeviceSearch.new(params.require(:device_search).permit!)
    end
  end

  def add_device_to_order
    if params[:service_order] && params[:device]
      @service_order = ServiceOrder.find_by(service_order: params[:service_order].to_i)
      unless @service_order.nil?
        ServiceDevice.create(service_order_fk: @service_order.service_order, device_fk: params[:device].to_i, service_device_status_type_fk: 1)
        redirect_to edit_service_request_service_order_path(@service_order.service_request, @service_order)
        flash[:info] = 'Uus toode lisatud'
        return
      end
    end
    redirect_to search_devices_path
  end

  private
  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:device, :device_type_fk, :name, :reg_no, :description, :model, :manufacturer, :service_order_id)
  end

  def get_params
    [
        name: "%#{params[:device_search][:name]}%",
        reg_no: "%#{params[:device_search][:reg_no]}%",
        description: "%#{params[:device_search][:description]}%",
        model: "%#{params[:device_search][:model]}%",
        manufacturer: "%#{params[:device_search][:manufacturer]}%",
        customer: "%#{params[:device_search][:client_name]}%",
        device_type_fk: params[:device_search][:device_type_fk].blank? ? nil : params[:device_search][:device_type_fk].to_i
    ]
  end

  def get_search_select
    sql = []
    where = get_where_clause
    sql << 'SELECT d.* FROM device d'
    unless params[:device_search][:client_name].blank?
      sql << 'LEFT JOIN service_device sd ON sd.device_fk = d.device'
      sql << 'LEFT JOIN service_order so ON sd.service_order_fk = so.service_order'
      sql << 'LEFT JOIN service_request sr ON so.service_request_fk = sr.service_request'
      sql << 'LEFT JOIN customer c ON sr.customer_fk = c.customer'
      sql << 'LEFT JOIN person p ON c.subject_fk = p.person AND c.subject_type_fk = 1'
      sql << 'LEFT JOIN enterprise e ON c.subject_fk = e.enterprise AND c.subject_type_fk = 2'
    end
    if where.size > 0
      sql << 'WHERE'
      sql << where.join(' AND ')
    end
    sql.join(' ')
  end

  def get_where_clause
    where = []
    where << 'd.name ILIKE :name' if has_device_param?(:name)
    where << 'd.reg_no ILIKE :reg_no' if has_device_param?(:reg_no)
    where << 'd.description ILIKE :description' if has_device_param?(:description)
    where << 'd.model ILIKE :model' if has_device_param?(:model)
    where << 'd.manufacturer ILIKE :manufacturer' if has_device_param?(:manufacturer)
    where << 'd.device_type_fk = :device_type_fk' if has_device_param?(:device_type_fk)
    unless params[:device_search][:client_name].blank?
      where << 'p.last_name ILIKE :customer OR e.name ILIKE :customer'
    end
    where
  end

  def has_device_param?(name)
    !params[:device_search][name].blank?
  end

end


class String
  def numeric?
    Float(self) != nil rescue false
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= bootstrap_form_for(@device, layout: :horizontal) do |f| %>
    <%= f.grouped_collection_select :device_type_fk, DeviceType.where(level:1),:sub_types, :label, :device_type, :type_name, control_col: "col-sm-2"  %>
    <%= f.text_field :name %>
    <%= f.text_field :reg_no %>
    <%= f.text_field :description %>
    <%= f.text_field :model %>
    <%= f.text_field :manufacturer %>
    <% if params[:service_order_id] %>
        <%= hidden_field :service_order, :id, value: params[:service_order_id].to_i %>
    <% end %>
    <%= f.form_group do %>
        <%= f.primary t('helpers.titles.save') %>
    <% end %>
<% end %>

app/views/devices/edit.html.erb
<%= provide(:title, 'Muuda seadme andmeid') %>
<%= render :partial => 'form' %>

app/views/devices/index.html.erb
<%- model_class = Device -%>
<%= provide(:title, 'Seadmed') %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:device_type_fk) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:reg_no) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:model) %></th>
    <th><%= model_class.human_attribute_name(:manufacturer) %></th>
    <th><%= t 'helpers.actions' %></th>
  </tr>
  </thead>
  <tbody>
  <% @devices.each do |device| %>
      <tr>
        <td><%= device.device_type.type_name %></td>
        <td><%= device.name %></td>
        <td><%= device.reg_no %></td>
        <td><%= device.description %></td>
        <td><%= device.model %></td>
        <td><%= device.manufacturer %></td>
        <td>
          <%= link_to t('helpers.links.edit'), edit_device_path(device), :class => 'btn btn-sm btn-default' %>
          <%= link_to t('helpers.links.destroy'), device_path(device),
                      :method => :delete, :data => {:confirm => t("helpers.links.confirm")},
                      :class => 'btn btn-sm btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= will_paginate @devices, renderer: BootstrapPagination::Rails %>
</div>

<%= link_to t('helpers.links.new'), new_device_path, :class => 'btn btn-primary' %>
<%= link_to 'Otsi seadet', search_devices_path, :class => 'btn btn-default' %>

app/views/devices/new.html.erb
<%= provide(:title, 'Lisa seade tellimusele') %>
<%= render :partial => 'form' %>

app/views/devices/new_service_device.html.erb
<div class="page-header">
  <h1>Lisa seade tellimusele</h1>
</div>
<%= render :partial => 'form' %>
<%= link_to 'Tagasi tellimuse juurde', :back %>

app/views/devices/search.html.erb
<%= bootstrap_form_for(@device_search, url: search_devices_path, layout: :horizontal) do |f| %>
    <%= f.grouped_collection_select :device_type_fk, DeviceType.where(level: 1), :sub_types, :label, :device_type, :type_name, include_blank: true, control_col: "col-sm-2" %>
    <%= f.text_field :name %>
    <%= f.text_field :reg_no %>
    <%= f.text_field :description %>
    <%= f.text_field :model %>
    <%= f.text_field :manufacturer %>
    <%= f.text_field :client_name, label: 'Klient' %>
    <% if params[:service_order_id].blank? %>
        <%= f.hidden_field :service_order_id %>
    <% else %>
        <%= f.hidden_field :service_order_id, value: params[:service_order_id].to_i %>
    <% end %>
    <%= f.form_group do %>
        <%= f.primary 'Otsi' %>
    <% end %>
<% end %>
<% if defined?(@devices) && @devices.size > 0 %>
    <%- model_class = Device -%>
    <table class="table table-striped">
      <thead>
      <tr>
        <th><%= model_class.human_attribute_name(:device_type_fk) %></th>
        <th><%= model_class.human_attribute_name(:name) %></th>
        <th><%= model_class.human_attribute_name(:reg_no) %></th>
        <th><%= model_class.human_attribute_name(:description) %></th>
        <th><%= model_class.human_attribute_name(:model) %></th>
        <th><%= model_class.human_attribute_name(:manufacturer) %></th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @devices.each do |device| %>
          <tr>
            <td><%= device.device_type.type_name %></td>
            <td><%= device.name %></td>
            <td><%= device.reg_no %></td>
            <td><%= device.description %></td>
            <td><%= device.model %></td>
            <td><%= device.manufacturer %></td>
            <td>
              <% unless @device_search.service_order_id.blank? %>
                  <%= link_to 'Lisa tellimusele', add_device_to_order_devices_path(device: device.device, service_order: @device_search.service_order_id) %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div>
      <%= will_paginate @devices, renderer: BootstrapPagination::Rails %>
    </div>
<% end %>

app/views/devices/show.html.erb
<%- model_class = Device -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:device) %>:</strong></dt>
  <dd><%= @device.device %></dd>
  <dt><strong><%= model_class.human_attribute_name(:device_type_fk) %>:</strong></dt>
  <dd><%= @device.device_type_fk %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @device.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reg_no) %>:</strong></dt>
  <dd><%= @device.reg_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @device.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:model) %>:</strong></dt>
  <dd><%= @device.model %></dd>
  <dt><strong><%= model_class.human_attribute_name(:manufacturer) %>:</strong></dt>
  <dd><%= @device.manufacturer %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              devices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_device_path(@device), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              device_path(@device),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>