config/routes.rb
Idu0200::Application.routes.draw do

  resources :devices do
    collection do
      get 'search'
      get 'add_device_to_order'
      post 'search'
    end
  end

  devise_for :user_accounts
  root :to => redirect('/service_requests')
  get 'customer/find_customer'
  get 'customer/find_employee'
  match '/get_default_price',  to: 'service_types#get_default_price',         via: 'get'
  match '/delete_service_action',  to: 'service_orders#delete_service_action',         via: 'delete'
  resources :service_requests do
    resources :service_orders do
    end
  end

end

app/models/service_request.rb
class ServiceRequest < ActiveRecord::Base
  self.table_name = 'service_request'
  self.primary_key = :service_request

  has_many :service_orders, foreign_key: 'service_request_fk'
  belongs_to :customer, foreign_key: 'customer_fk'
  belongs_to :employee, foreign_key: 'created_by'
  belongs_to :service_request_status_type, foreign_key: 'service_request_status_type_fk'

  def deletable?
    self.service_orders.count == 0
  end
end

app/controllers/service_requests_controller.rb
class ServiceRequestsController < ApplicationController
  before_action :authenticate_user_account!
  before_action :set_service_request, only: [:show, :edit, :update, :destroy]
  require 'will_paginate/array'

  # GET /service_requests
  # GET /service_requests.json
  def index
    @service_requests = ServiceRequest.includes(:service_request_status_type, employee:[:person], customer: [:person, :enterprise])
    .where(get_where_clause, *get_params)
    .order('service_request_status_type.type_name').paginate(:page => params[:page])
  end

  # GET /service_requests/1
  # GET /service_requests/1.json
  def show
  end

  # GET /service_requests/new
  def new
    @service_request = ServiceRequest.new
  end

  # GET /service_requests/1/edit
  def edit
  end

  # POST /service_requests
  # POST /service_requests.json
  def create
    @service_request = ServiceRequest.new(service_request_params)
    @service_request.created = Time.now
    @service_request.created_by = current_user_account.employee_id

    respond_to do |format|
      if @service_request.save
        format.html { redirect_to edit_service_request_path(@service_request), notice: 'Kliendi pöördumine registreeritud' }
        format.json { render action: 'show', status: :created, location: @service_request }
      else
        format.html { render action: 'new' }
        format.json { render json: @service_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_requests/1
  # PATCH/PUT /service_requests/1.json
  def update
    respond_to do |format|
      if @service_request.update(service_request_params)
        format.html { redirect_to edit_service_request_path(@service_request), notice: 'Kliendi pöördumine salvestatud' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @service_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_requests/1
  # DELETE /service_requests/1.json
  def destroy
    if @service_request.deletable?
      @service_request.destroy
    else
      flash[:error] = 'Pöördumisega on juba seotud tellimused'
    end
    respond_to do |format|
      format.html { redirect_to service_requests_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_request
      @service_request = ServiceRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_request_params
      params.require(:service_request).permit(:service_desc_by_customer, :service_desc_by_employee, :customer_fk, :service_request_status_type_fk)
    end

  def get_params
    [
        customer: "%#{params[:client]}%",
        service_request_status_type_fk: params[:service_request_status_type_fk]
    ]
  end

  def get_where_clause
    where = []
    where << 'service_request_status_type_fk = :service_request_status_type_fk' if has_param?(:service_request_status_type_fk)
    if has_param?(:client)
      where << 'person.last_name ILIKE :customer OR enterprise.name ILIKE :customer'
    end
    where.join(' AND ')
  end

  def has_param?(name)
    !params[name].blank?
  end
end

app/helpers/service_requests_helper.rb
module ServiceRequestsHelper
end

app/views/service_requests/_form.html.erb
<script>
    $(function () {
        $("#customer_search_box").autocomplete({
            source: "<%= customer_find_customer_path %>",
            minLength: 2,
            select: function (event, ui) {
                event.preventDefault();
                $("#service_request_customer_fk").val(ui.item.value);
                $("#customer_search_box").val(ui.item.label);
            }
        });
    });
</script>
<div class="row">
  <div class="col-sm-3 col-sm-offset-1">
    <%= bootstrap_form_for @service_request do |f| %>
        <%= f.label :customer_fk %>
        <%= f.form_group do %>
            <%= f.hidden_field :customer_fk %>
            <input type="text" id="customer_search_box" class="form-control" value="<%= f.object.customer.get_name unless f.object.customer.nil? %>">
        <% end %>
        <%= f.text_area :service_desc_by_customer %>
        <%= f.text_area :service_desc_by_employee %>
        <%= f.collection_select :service_request_status_type_fk, ServiceRequestStatusType.all, :service_request_status_type, :type_name, :class => 'text_field' %>
        <%= f.submit t('helpers.titles.save'), :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    service_requests_path, :class => 'btn' %>

    <% end %>
  </div>
</div>

app/views/service_requests/edit.html.erb
<%= provide(:title, 'Muuda pöördumise infot') %>
<%= render :partial => 'form' %>
<br>
<%= link_to 'Halda tellimusi', service_request_service_orders_path(service_request_id: params[:id].to_i), class: 'btn btn-info col-sm-offset-1' %>

app/views/service_requests/index.html.erb
<%- model_class = ServiceRequest -%>
<%= provide(:title, 'Kliendi pöördumised') %>
<%= bootstrap_form_for '', layout: :horizontal, method: :get do |f| %>
    <%= f.search_field :client, label: 'Klient', value: params[:client] %>
    <%= f.collection_select :service_request_status_type_fk, ServiceRequestStatusType.all, :service_request_status_type, :type_name, include_blank: true, control_col: 'col-sm-2', label: 'Seisund', selected: params[:service_request_status_type_fk] %>
    <%= f.submit 'Otsi', class: 'btn btn-success' %>
<% end %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:customer_fk) %></th>
    <th><%= model_class.human_attribute_name(:created_by) %></th>
    <th><%= model_class.human_attribute_name(:created) %></th>
    <th><%= model_class.human_attribute_name(:service_desc_by_customer) %></th>
    <th><%= model_class.human_attribute_name(:service_desc_by_employee) %></th>
    <th><%= model_class.human_attribute_name(:service_request_status_type_fk) %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @service_requests.each do |service_request| %>
      <tr>
        <td><%= service_request.customer.name %></td>
        <td><%= service_request.employee.person.full_name %></td>
        <td><%= service_request.created.strftime("%F %T") %></td>
        <td><%= service_request.service_desc_by_customer %></td>
        <td><%= service_request.service_desc_by_employee %></td>
        <td><%= service_request.service_request_status_type.type_name %></td>
        <td><%= link_to 'Vaata tellimusi', service_request_service_orders_path(service_request) %></td>
        <td>
          <%= link_to t('helpers.links.edit'), edit_service_request_path(service_request), :class => 'btn btn-sm btn-default' %>
          <%= link_to t('helpers.links.destroy'),
                      service_request_path(service_request),
                      :method => :delete,
                      :data => {:confirm => t('helpers.links.confirm')},
                      :class => 'btn btn-sm btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<div>
  <%= will_paginate @service_requests, renderer: BootstrapPagination::Rails %>
</div>
<%= link_to t('helpers.links.new'), new_service_request_path, :class => 'btn btn-primary' %>

app/views/service_requests/new.html.erb
<%= provide(:title, 'Registreeri uus pöördumine') %>
<%= render :partial => 'form' %>

app/views/service_requests/show.html.erb
<%- model_class = ServiceRequest -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal col-sm-12">
  <dt><strong><%= model_class.human_attribute_name(:customer_fk) %>:</strong></dt>
  <dd><%= @service_request.customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_by) %>:</strong></dt>
  <dd><%= @service_request.employee.person.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created) %>:</strong></dt>
  <dd><%= @service_request.created.strftime("%F %T") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_desc_by_customer) %>:</strong></dt>
  <dd><%= @service_request.service_desc_by_customer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_desc_by_employee) %>:</strong></dt>
  <dd><%= @service_request.service_desc_by_employee %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_request_status_type_fk) %>:</strong></dt>
  <dd><%= @service_request.service_request_status_type.type_name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              service_requests_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_request_path(@service_request), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_request_path(@service_request),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>