config/routes.rb
Idu0200::Application.routes.draw do

  resources :devices do
    collection do
      get 'search'
      get 'add_device_to_order'
      post 'search'
    end
  end

  devise_for :user_accounts
  root :to => redirect('/service_requests')
  get 'customer/find_customer'
  get 'customer/find_employee'
  match '/get_default_price',  to: 'service_types#get_default_price',         via: 'get'
  match '/delete_service_action',  to: 'service_orders#delete_service_action',         via: 'delete'
  resources :service_requests do
    resources :service_orders do
    end
  end

end

app/models/service_order.rb
class ServiceOrder < ActiveRecord::Base
  self.table_name = 'service_order'
  self.primary_key = :service_order
  include ServiceOrdersHelper

  has_many :service_parts, foreign_key: 'service_order_fk'
  has_many :service_actions, foreign_key: 'service_order_fk'
  has_many :service_devices, foreign_key: 'service_order_fk'
  belongs_to :so_status_type, foreign_key: 'so_status_type_fk'
  belongs_to :creator, foreign_key: 'created_by', :class_name => "Employee"
  belongs_to :updater, foreign_key: 'updated_by', :class_name => "Employee"
  belongs_to :status_changer, foreign_key: 'status_changed_by', :class_name => "Employee"
  belongs_to :service_request, foreign_key: 'service_request_fk'

  accepts_nested_attributes_for :service_devices
  accepts_nested_attributes_for :service_actions, :allow_destroy => true
  accepts_nested_attributes_for :service_parts, :allow_destroy => true

  before_save :calculate_prices


  def status_changer_name
    if status_changed_by.nil?
      ''
    else
      status_changer.name
    end
  end

  def updater_name
    if updated_by.nil?
      ''
    else
      updater.name
    end
  end

  def calculate_prices
    total_price = 0
    service_actions.each do |action|
      sum = action.service_amount.to_f * action.price.to_f
      total_price += sum
    end
    service_parts.each do |part|
      sum = part.part_count.to_f * part.part_price.to_f
      total_price += sum
    end
    self.price_total = total_price
  end

  def edit_sub_records?
    so_status_type_fk == SoStatusType::VASTU_VOETUD
  end

  def deletable?
    self.service_devices.count == 0 && self.service_actions.count == 0 && self.service_parts.count == 0
  end

  validate do |service_order|
    validate_service_order(service_order)
  end

end

app/controllers/service_orders_controller.rb
class ServiceOrdersController < ApplicationController
  before_action :set_service_order, only: [:show, :edit, :update, :destroy]
  before_action :set_service_request, except: [:delete_service_action]

  # GET /service_orders
  # GET /service_orders.json
  def index
    @service_orders = ServiceOrder.where(service_request_fk: @service_request.id)
    .includes(:so_status_type, creator:[:person], updater:[:person],status_changer:[:person])
    .order('so_status_type.type_name')
  end

  # GET /service_orders/1
  # GET /service_orders/1.json
  def show
  end

  # GET /service_orders/new
  def new
    @service_order = @service_request.service_orders.build
  end

  # GET /service_orders/1/edit
  def edit
    add_empty_sub_objects
  end

  def add_empty_sub_objects
    if @service_order.edit_sub_records?
      @service_order.service_actions.build
      @service_order.service_parts.build
    end
  end

  # POST /service_orders
  # POST /service_orders.json
  def create
    @service_order = ServiceOrder.new(service_order_params)
    @service_order.created = Time.now
    @service_order.created_by = current_user_account.employee_id
    @service_order.so_status_type_fk = SoStatusType::VASTU_VOETUD
    @service_request.service_orders << @service_order

    respond_to do |format|
      if @service_request.save
        format.html { redirect_to edit_service_request_service_order_path(@service_request, @service_order), notice: 'Uus tellimus lisatud' }
        format.json { render action: 'show', status: :created, location: @service_order }
      else
        format.html { render action: 'new' }
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /service_orders/1
  # PATCH/PUT /service_orders/1.json
  def update
    @service_order.updated = Time.now
    @service_order.updated_by = current_user_account.employee_id
    @service_order.attributes = service_order_params

    save_nested_objects

    if @service_order.changed.include?('so_status_type_fk')
      @service_order.status_changed_by = current_user_account.employee_id
      @service_order.status_changed = Time.now
    end
    respond_to do |format|
      if @service_order.save
        format.html { redirect_to edit_service_request_service_order_path(@service_request, @service_order), notice: 'Tellimuse andmed uuendatud' }
        format.json { head :no_content }
      else
        format.html do
          flash.now[:error] = @service_order.errors.to_a
          add_empty_sub_objects
          render action: 'edit'
        end
        format.json { render json: @service_order.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /service_orders/1
  # DELETE /service_orders/1.json
  def destroy
    if @service_order.deletable?
      @service_order.destroy
    else
      flash[:error] = 'Tellimusega on juba seotud teised objektid'
    end
    respond_to do |format|
      format.html { redirect_to service_request_service_orders_url }
      format.json { head :no_content }
    end
  end

  def delete_service_action
    id = params[:id]
    sa = ServiceAction.find_by(service_action: id.to_i)
    so = sa.service_order
    url = edit_service_request_service_order_path(so.service_request, so)
    sa.destroy
    redirect_to url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_service_order
    @service_order = ServiceOrder.find(params[:id])
  end

  def set_service_request
    @service_request = ServiceRequest.find(params[:service_request_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def service_order_params
    params.require(:service_order).permit(:service_request_fk, :service_order, :so_status_type_fk, :note)
  end

  def separate_sub_objects(form_params, primary_key)
    updatable_objects = []
    new_objects = []
    if params[:service_order] && params[:service_order][form_params]
      params[:service_order][form_params].to_hash.values.each do |zi|
        if zi.key?(primary_key.to_s) && !zi[primary_key.to_s].blank?
          updatable_objects[zi[primary_key.to_s].to_i] = zi
        elsif block_given?
          new_objects << zi if yield(zi)
        else
          new_objects << zi
        end
      end

    end
    {update: updatable_objects, create: new_objects}
  end

  def update_existing_objects(objects, form_objects, primary_key)
    objects.each do |object|
      object.attributes = form_objects[object.send(primary_key)]
    end
  end

  def create_new_objects(clazz, new_objects)
    objects = []
    new_objects.each do |object_hash|
      object = clazz.new(object_hash)
      if object.respond_to?('created')
        object.created = Time.now
      end
      if object.respond_to?('created_by')
        object.created_by = current_user_account.employee_id
      end
      objects << object
    end
    objects
  end

  def save_nested_objects
    service_devices = separate_sub_objects(:service_devices_attributes, :service_device)
    if service_devices[:update]
      update_existing_objects(@service_order.service_devices, service_devices[:update], :service_device)
    end

    service_actions = separate_sub_objects(:service_actions_attributes, :service_action) do |object_hash|
      !object_hash['service_amount'].blank?
    end
    update_existing_objects(@service_order.service_actions, service_actions[:update], :service_action)
    @service_order.service_actions << create_new_objects(ServiceAction, service_actions[:create])


    service_parts = separate_sub_objects(:service_parts_attributes, :service_part) do |object_hash|
      !object_hash['part_count'].blank?
    end
    update_existing_objects(@service_order.service_parts, service_parts[:update], :service_part)
    @service_order.service_parts << create_new_objects(ServicePart, service_parts[:create])
  end
end

app/helpers/service_orders_helper.rb
module ServiceOrdersHelper

  def validate_service_order(service_order)
    validate_status(service_order)
    validate_devices_statuses(service_order)

  end

  def validate_status(service_order)
    case service_order.so_status_type_fk
      when SoStatusType::VASTU_VOETUD
        # No validation needed
      else
        service_order.service_devices.each do |device|
          if device.service_device_status_type_fk == ServiceDeviceStatusType::VASTU_VOETUD
            service_order.errors.add(:base, 'Pöördumise seisundit ei saa muuta sest kõik seadmed pole valmis seisundis')
            return
          end
        end
        service_order.service_actions.each do |service_action|
          if service_action.service_action_status_type_fk == ServiceActionStatusType::POOLELI
            service_order.errors.add(:base, 'Pöördumise seisundit ei saa muuta sest kõik tööd pole veel valmis')
            return
          end
        end
    end
  end

  def validate_devices_statuses(service_order)
    service_order.service_devices.each do |device|
      if device.service_device_status_type_fk != ServiceDeviceStatusType::VASTU_VOETUD
        service_order.service_actions.each do |sa|
          if sa.service_device_fk == device.service_device && sa.service_action_status_type_fk == ServiceActionStatusType::POOLELI
            service_order.errors.add(:base, 'Seadme seisundit ei saa muuta sest sellega seotud tööd pole veel lõpetatud')
            return
          end
        end

      end
    end

  end
end

app/views/service_orders/_form.html.erb
<% content_for :javascript_includes do %>
    <%= javascript_include_tag 'service_orders' %>
<% end %>
<%= bootstrap_nested_form_for([@service_request, @service_order], layout: :horizontal) do |f| %>

    <%= f.text_area :note, control_col:'col-sm-3', rows:4 %>
    <% unless @service_order.id.blank? %>
        <%= f.collection_select :so_status_type_fk, SoStatusType.all, :so_status_type, :type_name, control_col: 'col-sm-2' %>
        <%= f.static_control :price_total %>
        <%= render 'service_devices', f: f %>
        <% if @service_order.edit_sub_records? %>
            <%= render 'service_actions', f: f %>
            <%= render 'service_parts', f: f %>
        <% else %>
            <%= render 'service_actions_show' %>
            <%= render 'service_parts_show' %>
        <% end %>
    <% end %>

    <%= f.primary t('helpers.titles.save') %>

<% end %>
<%= link_to 'Tagasi tellimuste juurde', service_request_service_orders_path(@service_request), class: 'btn btn-default' %>

app/views/service_orders/_service_actions.erb
<h3 class="sub-title">Tellimusega seotud tööd</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Tüüp</th>
    <th>Seisund</th>
    <th>Kogus</th>
    <th>Hind (€)</th>
    <th>Ühik</th>
    <th>Hind kokku (€)</th>
    <th>Kirjeldus</th>
    <th>Seotud seadmega</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @service_order.service_actions.each do |service_action| %>
      <%= f.fields_for :service_actions, service_action, id_field: false, wrapper: false do |saf| %>
          <tr class="fields">
            <td>
              <%= saf.hidden_field :service_action %>
              <%= saf.collection_select_without_bootstrap :service_type_fk, ServiceType.all, :service_type, :type_name, {}, {class: 'service_type form-control'} %>
            </td>
            <td><%= saf.collection_select_without_bootstrap :service_action_status_type_fk, ServiceActionStatusType.all, :service_action_status_type, :type_name, {}, {class: 'form-control'} %></td>
            <td width="100px"><%= saf.number_field_without_bootstrap :service_amount, class: 'form-control col-sm 2' %></td>
            <td><%= saf.text_field_without_bootstrap :price, class: 'unit_price form-control', :size => '5', data:{initial:true} %></td>
            <td><span class='unit_type'></span></td>
            <td><%= service_action.price_total %></td>
            <td><%= saf.text_field_without_bootstrap :action_description, class: 'form-control' %></td>
            <td><%= saf.collection_select_without_bootstrap :service_device_fk, @service_order.service_devices, :service_device, :name, {include_blank:true}, {class: 'form-control'} %></td>
            <td><%= saf.link_to_remove 'X', class: 'btn btn-danger' %></td>
          </tr>
      <% end %>
  <% end %>
  <tr>
    <td><%= f.link_to_add 'Lisa', :service_actions, class: 'btn btn-success' %></td>
  </tr>
  </tbody>
</table>

app/views/service_orders/_service_actions_show.erb
<h3 class="sub-title">Tellimusega seotud tööd</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Tüüp</th>
    <th>Seisund</th>
    <th>Kogus</th>
    <th>Hind (€)</th>
    <th>Ühik</th>
    <th>Hind kokku (€)</th>
    <th>Kirjeldus</th>
    <th>Seotud seadmega</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @service_order.service_actions.each do |service_action| %>
      <tr>
        <td><%= service_action.service_type.type_name %></td>
        <td><%= service_action.service_action_status_type.type_name %></td>
        <td><%= service_action.service_amount %></td>
        <td><%= service_action.price %></td>
        <td><%= service_action.service_type.service_unit_type.type_name %></td>
        <td><%= service_action.price_total %></td>
        <td><%= service_action.action_description %></td>
        <td><%= service_action.service_device.name unless service_action.service_device_fk.nil? %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/service_orders/_service_devices.erb
<h3 class="sub-title">Tellimusega seotud seadmed</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Kirjeldus</th>
    <th>Seisund</th>
    <th>Seisund muudetud</th>
    <th>Tüüp</th>
    <th>Nimetus</th>
    <th>Number</th>
    <th>Tootja</th>
    <th>Mudel</th>
  </tr>
  </thead>
  <tbody>
  <% @service_order.service_devices.each do |service_device| %>
      <%= f.fields_for :service_devices, service_device, id_field: false do |sdf| %>
          <tr class="fields">
            <%= sdf.hidden_field :service_device %>
            <td><%= sdf.text_field_without_bootstrap :service_description, class:'form-control' %></td>
            <td><%= sdf.collection_select_without_bootstrap :service_device_status_type_fk, ServiceDeviceStatusType.all, :service_device_status_type, :type_name,{},{class:'form-control'} %></td>
            <td><%= format_time(service_device.status_changed) %></td>
            <td><%= service_device.device.device_type.type_name %></td>
            <td><%= service_device.device.name %></td>
            <td><%= service_device.device.reg_no %></td>
            <td><%= service_device.device.manufacturer %></td>
            <td><%= service_device.device.model %></td>
            <td><%= sdf.link_to_remove 'X', class: 'btn btn-danger' if service_device.valid_to_delete? %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>
<%= link_to 'Lisa uus seade', new_device_path(service_order_id:@service_order.service_order), class: 'btn btn-info' %>
<%= link_to 'Otsi seadet', search_devices_path(service_order_id:@service_order.service_order), class: 'btn btn-info' %>
<a class="toggle-next"></a>

app/views/service_orders/_service_parts.erb
<h3 class="sub-title">Tellimusega seotud varuosad</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Nimi</th>
    <th>Seeria nr</th>
    <th>Kogus</th>
    <th>Hind (€)</th>
    <th>Seotud seadmega</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @service_order.service_parts.each do |service_part| %>
      <%= f.fields_for :service_parts, service_part, id_field: false, wrapper: false do |saf| %>
          <tr class="fields">
            <td>
              <%= saf.hidden_field :service_part %>
              <%= saf.text_field_without_bootstrap :part_name, class: 'form-control' %>
            </td>
            <td><%= saf.text_field_without_bootstrap :serial_no, class: 'form-control' %></td>
            <td><%= saf.text_field_without_bootstrap :part_count, class: 'form-control' %></td>
            <td><%= saf.text_field_without_bootstrap :part_price, class: 'form-control' %></td>
            <td><%= saf.collection_select_without_bootstrap :service_device_fk, @service_order.service_devices, :service_device, :name, {include_blank:true}, {class: 'form-control'} %></td>
            <td><%= saf.link_to_remove 'X', class: 'btn btn-danger' %></td>
          </tr>
      <% end %>
  <% end %>
  <tr>
    <td><%= f.link_to_add 'Lisa', :service_parts, class: 'btn btn-success' %></td>
  </tr>
  </tbody>
</table>

app/views/service_orders/_service_parts_show.erb
<h3 class="sub-title">Tellimusega seotud varuosad</h3>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Nimi</th>
    <th>Seeria nr</th>
    <th>Kogus</th>
    <th>Hind (€)</th>
    <th>Seotud seadmega</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @service_order.service_parts.each do |service_part| %>
      <tr>
        <td><%= service_part.part_name %></td>
        <td><%= service_part.serial_no %></td>
        <td><%= service_part.part_count %></td>
        <td><%= service_part.part_price %></td>
        <td><%= service_part.service_device.name unless service_part.service_device_fk.nil? %></td>
       </tr>
      <% end %>
  </tbody>
</table>

app/views/service_orders/edit.html.erb
<% provide(:title, 'Muuda tellimust') %>
<%= render :partial => 'form' %>

app/views/service_orders/index.html.erb
<%- model_class = ServiceOrder -%>
<%= provide(:title, 'Tellimused') %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:so_status_type_fk) %></th>
    <th><%= model_class.human_attribute_name(:created_by) %></th>
    <th><%= model_class.human_attribute_name(:updated_by) %></th>
    <th><%= model_class.human_attribute_name(:created) %></th>
    <th><%= model_class.human_attribute_name(:updated) %></th>
    <th><%= model_class.human_attribute_name(:status_changed) %></th>
    <th><%= model_class.human_attribute_name(:status_changed_by) %></th>
    <th><%= model_class.human_attribute_name(:price_total) %></th>
    <th><%= model_class.human_attribute_name(:note) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @service_orders.each do |service_order| %>
      <tr>
        <td><%= service_order.so_status_type.type_name %></td>
        <td><%= service_order.creator.name %></td>
        <td><%= service_order.updater_name %></td>
        <td><%= format_time(service_order.created) %></td>
        <td><%= format_time(service_order.updated) %></td>
        <td><%= format_time(service_order.status_changed) %></td>
        <td><%= service_order.status_changer_name %></td>
        <td><%= service_order.price_total %></td>
        <td><%= service_order.note %></td>
        <td>
          <%= link_to t('helpers.links.edit'), edit_service_request_service_order_path(service_order.service_request_fk, service_order), :class => 'btn btn-sm btn-default' %>
          <%= link_to t('helpers.links.destroy'),
                      service_request_service_order_path(service_order.service_request_fk, service_order),
                      :method => :delete,
                      :data => {:confirm => t('helpers.links.confirm')},
                      :class => 'btn btn-sm btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('helpers.links.new'), new_service_request_service_order_path, :class => 'btn btn-primary' %>

app/views/service_orders/new.html.erb
<%= provide(:title, 'Uus tellimus') %>
<%= render :partial => 'form' %>

app/views/service_orders/show.html.erb
<%- model_class = ServiceOrder -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:service_order) %>:</strong></dt>
  <dd><%= @service_order.service_order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:so_status_type_fk) %>:</strong></dt>
  <dd><%= @service_order.so_status_type_fk %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_by) %>:</strong></dt>
  <dd><%= @service_order.created_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:service_request_fk) %>:</strong></dt>
  <dd><%= @service_order.service_request_fk %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated_by) %>:</strong></dt>
  <dd><%= @service_order.updated_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created) %>:</strong></dt>
  <dd><%= @service_order.created %></dd>
  <dt><strong><%= model_class.human_attribute_name(:updated) %>:</strong></dt>
  <dd><%= @service_order.updated %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_changed) %>:</strong></dt>
  <dd><%= @service_order.status_changed %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_changed_by) %>:</strong></dt>
  <dd><%= @service_order.status_changed_by %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price_total) %>:</strong></dt>
  <dd><%= @service_order.price_total %></dd>
  <dt><strong><%= model_class.human_attribute_name(:note) %>:</strong></dt>
  <dd><%= @service_order.note %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              service_request_service_orders_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_service_request_service_order_path(@service_request,@service_order), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              service_request_service_order_path(@service_request,@service_order),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>