config/routes.rb
Idu0200::Application.routes.draw do

  resources :devices do
    collection do
      get 'search'
      get 'add_device_to_order'
      post 'search'
    end
  end

  devise_for :user_accounts
  root :to => redirect('/service_requests')
  get 'customer/find_customer'
  get 'customer/find_employee'
  match '/get_default_price',  to: 'service_types#get_default_price',         via: 'get'
  match '/delete_service_action',  to: 'service_orders#delete_service_action',         via: 'delete'
  resources :service_requests do
    resources :service_orders do
    end
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
    self.table_name = 'address'
    self.primary_key = :address

end

app/models/address_type.rb
class AddressType < ActiveRecord::Base
    self.table_name = 'address_type'
    self.primary_key = :address_type

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    self.table_name = 'contact'
    self.primary_key = :contact

end

app/models/contact_type.rb
class ContactType < ActiveRecord::Base
    self.table_name = 'contact_type'
    self.primary_key = :contact_type

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  self.table_name = 'customer'
  self.primary_key = :customer

  belongs_to :person, -> { where 'customer.subject_type_fk' => 1 }, foreign_key: 'subject_fk'
  belongs_to :enterprise, -> { where 'customer.subject_type_fk' => 2 }, foreign_key: 'subject_fk'

  PERSON = 1
  ENTERPRISE = 2

  def name
    if is_person?
      self.person.first_name + ' ' +self.person.last_name
    elsif is_enterprise?
      self.enterprise.name
    else
      ''
    end
  end

  def is_person?
    subject_type_fk == PERSON
  end

  def is_enterprise?
    subject_type_fk == ENTERPRISE
  end

  def self.join_sql
    ' LEFT JOIN "person" ON "person"."person" = "customer"."subject_fk" AND "customer"."subject_type_fk" = 1
  LEFT JOIN "enterprise" ON "enterprise"."enterprise" = "customer"."subject_fk" AND "customer"."subject_type_fk" = 2'
  end

  def get_name
    if sub_object.nil?
      return ''
    end
    if is_person?
      sub_object.first_name + ' ' +sub_object.last_name
    elsif is_enterprise?
      sub_object.name
    end
  end

  def sub_object
    unless @sub_object.nil?
      return @sub_object
    end
    if is_person?
      @sub_object = Person.find_by(person: subject_fk)
    elsif is_enterprise?
      @sub_object = Enterprise.find_by(enterprise: subject_fk)
    end
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  self.table_name = 'device'
  self.primary_key = :device
  belongs_to :device_type, foreign_key: 'device_type_fk'
  has_many :service_devices, foreign_key: 'device_fk'

  validates_presence_of :name
  validates_length_of :reg_no, maximum: 100
  validates_format_of :manufacturer, :with => /\A[A-Za-z ]+\Z/, message: 'Ainult tähed on lubatud'

end

app/models/device_search.rb
class DeviceSearch < Device
  attr_accessor  :client_name, :service_order_id
end

app/models/device_type.rb
class DeviceType < ActiveRecord::Base
    self.table_name = 'device_type'
    self.primary_key = :device_type

    def sub_types
      DeviceType.where(level:2, super_type_fk:self.device_type)
    end

    def label
      self.type_name
    end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
    self.table_name = 'employee'
    self.primary_key = :employee

  belongs_to :person, foreign_key: 'person_fk'

  def name
    person.full_name
  end

end

app/models/employee_role.rb
class EmployeeRole < ActiveRecord::Base
    self.table_name = 'employee_role'
    self.primary_key = :employee_role

end

app/models/enterprise.rb
class Enterprise < ActiveRecord::Base
    self.table_name = 'enterprise'
    self.primary_key = :enterprise

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
    self.table_name = 'invoice'
    self.primary_key = :invoice

end

app/models/invoice_row.rb
class InvoiceRow < ActiveRecord::Base
    self.table_name = 'invoice_row'
    self.primary_key = :invoice_row

end

app/models/person.rb
class Person < ActiveRecord::Base
  self.table_name = 'person'
  self.primary_key = :person

  def full_name
    first_name + ' '+ last_name
  end

end

app/models/service_note.rb
class ServiceNote < ActiveRecord::Base
    self.table_name = 'service_note'
    self.primary_key = :service_note

end

app/models/service_part.rb
class ServicePart < ActiveRecord::Base
    self.table_name = 'service_part'
    self.primary_key = :service_part

    belongs_to :service_device, foreign_key: 'service_device_fk'

    attr_accessor :_destroy
    validates_numericality_of :part_count
    validate :check_serial
    validates_presence_of :part_price
    validates_numericality_of :part_price

    def _destroy=(val)
      if val == '1'
        mark_for_destruction
      end
    end

    def check_serial
      if !serial_no.blank? && part_count > 1
        errors.add(:part_count, 'peab olema 1 kui seeria nr on sisestatud')
      end
    end
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
    self.table_name = 'service_type'
    self.primary_key = :service_type
    belongs_to :service_unit_type, foreign_key: 'service_unit_type_fk'

end

app/models/struct_unit.rb
class StructUnit < ActiveRecord::Base
    self.table_name = 'struct_unit'
    self.primary_key = :struct_unit

end

app/models/subject_type.rb
class SubjectType < ActiveRecord::Base
    self.table_name = 'subject_type'
    self.primary_key = :subject_type

end

app/models/user_account.rb
class UserAccount < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable

  self.table_name = 'user_account'
  self.primary_key = :user_account

  def encrypted_password
    passw
  end

  def encrypted_password=(value)
    @passw = value
  end

  def valid_password?(password)
    self.passw == Digest::MD5.hexdigest(password) ||
        self.passw == password
  end


  def employee_id
    if subject_type_fk == 3
      return subject_fk
    end
    nil
  end
end

app/views/layouts/_header.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">CarFix</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Pöördumised', service_requests_path %></li>
        <li><%= link_to 'Seadmed', devices_path %></li>
        <!--<li class="dropdown">-->
          <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown-->
            <!--<span class="caret"></span></a>-->
          <!--<ul class="dropdown-menu" role="menu">-->
            <!--<li><a href="#">Action</a></li>-->
            <!--<li><a href="#">Another action</a></li>-->
            <!--<li><a href="#">Something else here</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="#">Separated link</a></li>-->
            <!--<li class="divider"></li>-->
            <!--<li><a href="#">One more separated link</a></li>-->
          <!--</ul>-->
        <!--</li>-->
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_account_signed_in? %>
            <li>
              <%= link_to('Logi välja', destroy_user_account_session_path, :method => :delete) %>
            </li>
        <% end %>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<%# flash types are: info, success, warning, danger %>

<% message_map = {}
   flash.each do |name, msg|
     if message_map.key?(name)
       message_map[name].push(msg)
     else
       if msg.is_a?(String)
         message_map[name] = [msg]
       elsif msg.is_a?(Array)
         message_map[name] = msg
       end
     end

   end %>

<% message_map.each_key do |key| %>
    <% if message_map[key].size == 0 %>
        <% next %>
    <% end %>

    <div class="alert <%= bootstrap_class_for(key) %> alert-dismissable">
      <button key="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <% message_map[key].each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Idu0200" %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', :media => "all" %>
  <%= javascript_include_tag 'application' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= yield :javascript_includes %>

</head>
<body>

<%= render 'layouts/header' %>

<div class="container-fluid">
    <h2><%= content_for?(:title) ? yield(:title) : '' %></h2>
  <div id="messages-container">
    <%= render 'layouts/messages' %>
  </div>
  <%= yield %>


  <footer>
    <p>&copy; Alar Rõa</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>